services:
  base:
    build:
      context: .
      dockerfile: php.dockerfile
    image: big-avalanche/base:latest

  app:
    build:
      context: .
      dockerfile: laravel.dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    # ports:
    # - ${REVERB_PORT}:${REVERB_PORT}
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - laravel
    depends_on:
      - base

    # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "0:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 0:80
    networks:
      - laravel

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "0:6379"
  #   networks:
  #     - laravel

  # cron:
  #   restart: unless-stopped
  #   build:
  #     context: ./
  #     dockerfile: ./cron.dockerfile
  #   # run crond as main process of container
  #   entrypoint: ["bash", "-c", "cron -f"]
  #   volumes:
  #     - ./:/var/www
  #   depends_on:
  #     - app
  #     - base
  #   networks:
  #     - laravel

  # soketi:
  #   image: "quay.io/soketi/soketi:latest-16-alpine"
  #   environment:
  #     SOKETI_DEBUG: "1"
  #     SOKETI_METRICS_SERVER_PORT: "9601"
  #   ports:
  #     - "${PUSHER_PORT:-6001}:6001"
  #     - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
  #   networks:
  #     - laravel

  # supervisor:
  #   restart: unless-stopped
  #   build:
  #     context: .
  #     dockerfile: supervisor.dockerfile
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #     - ${REVERB_PORT}:${REVERB_PORT}
  #   depends_on:
  #     - app
  #     - base
  #   networks:
  #     - laravel

networks:
  laravel:
    driver: bridge
